apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-name
spec: 
  template: 
    spec:
      containers: 
      - name: container-name
        image: container-image
        #COPY file
---
#2 deployments og 1 service
